sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: pjGxMzq0TlwjfrYpmzy07GutrigxtN6+Iry9xGro9y+RnotrbYWHoS24WVtO2MyHnh3hAHJWLynqdyCA6KFSYTg+vYrAgoxBDSM8Zdk5DDmzc1MoOTtE99Bdg/UWNBK4LDSxL3l1CDJz4p6hRlmizRvN+Ta/0W95pJf/sMfe1GjGpO2swhr0cikyj6e70HjCFlSsvT0K+vStUZ8j5mntFV7ICjnrBkGD74gXUwT6cU/Yn/GpR1Xk0CDeM+EYXBqIaFmdHrVhErTRY6GZdAwjP8o2cFkvMfaQoOqELOAiYLTxvud2PkywlPuN2qr5IL3fASaIpY3t9WreVMeINDk7DnI0a7xckOEzEz1uuBIOam4oFqhQuZkc1VKgdCtO8a7oJwXXqxZ4a7piBHSyOvOINMbSp5cIMuPeNIUU7Dh9vCUjleTJdffAFsCTR6XaUfh5JaZDT+0sdW7zPEv2OMIAvn7T60w79Gsnx17Vuk/SSGnME5Lnv1epipvDk3ayBP+jLYD4cybCisjqJuFm+ly9gQXb5W3ziatQAQIU5G5hXML5bXjthbhd+zQIlXNR23OjEZqNxREuTgvKgtHLMoijItbfbiX41GeA2rRUC6e9/Nc6q9oHWIpy2ZyRWN2ebQT6PCiLo+rhIqD12Uos/d+lxWkWsbY6ag2PMhcyb5MFYr0=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Confessions-of-Harry-Lorrequer---Volume-1_5234
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy